### PR TITLE
Relax omniauth-shopify-oauth2 constraint

### LINKED ISSUE #90: Upgrade dependency on oauth2 to 1.6?
At the moment this gem is dependent on omniauth-oauth2 1.5, but a new version has been out since 2018(v1.6). Can we update the dependency to allow 1.6?

https://github.com/Shopify/omniauth-shopify-oauth2/blob/2359fe8229add27afb88eeebbe7306a8e4ed1451/omniauth-shopify-oauth2.gemspec#L20

### PR DESCRIPTION
**Pull request by andyw8**
Fixes #90

### CODE REVIEW

**Review by paulomarg — APPROVED** [review]

**Comment by erichmachado** [comment]
Hi @andyw8 and @paulomarg, I'm sorry to bother you with this. I would like to know if you have a timeline planned for the updated gem release.

**Comment by andyw8** [comment]
@erichmachado I'll prepare a release.

**Comment by andyw8** [comment]
https://rubygems.org/gems/omniauth-shopify-oauth2/versions/2.3.0 is now available

**Comment by erichmachado** [comment]
That's awesome! Thank you @andyw8! 🎉

**Pull request merged**
