### PR TITLE
Add shop_id to extra hash

### PR DESCRIPTION
**Pull request by SebastianSzturo**
Depends on https://github.com/Shopify/shopify/pull/79849

- Add `shop_id` to the extra hash.

🎩 'ed in development.

For Review: @EiNSTeiN- @kevinhughes27

### CODE REVIEW

**Comment by SebastianSzturo** [comment]
Ruby 2.1.0 tests also fail on master; anything I can do about it?

**Comment by kevinhughes27** [comment]
its a rack version issue

**Comment by EiNSTeiN-** [comment]
LGTM

**Comment by SebastianSzturo** [comment]
Closing this for now. We will to the instafacts team to make sure we can join trekkie data with the shopify domain instead of patching this into shopify core and the oauth gem.

**Pull request closed without merging**
